### ISSUE TITLE
In browser support for tunneling TURN traffic thru webtransport.

### ISSUE THREAD

**Issue by unicomp21** [w3c/p2p-webtransport#138]
Does that make sense?

**Comment by aboba** [comment]
WebTransport is a client/server protocol which assumes a connection initiated by the client to a server available on the public Internet.   Since WebTransport is defined over HTTP/3 and HTTP/2, it can utilize QUIC/UDP or TCP to establish a connection. 

As a result, there is no reason to tunnel WebTransport via TURN.
